import getSite from "@/lib/api";
import { notFound } from "next/navigation";
import { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { getFont, getAllFontVariables } from "@/lib/fonts";
import { getColorTheme, getColorThemeMetadata } from "@/themes/index";
import { getTemplate } from "@/templates";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function DomainLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ domain: string }>;
}>) {
    const { domain } = await params;
    const siteData = await getSite(domain);

    // Get configuration from site data or use defaults
    const colorThemeSlug = siteData?.theme || "default";
    const templateSlug = siteData?.template || "default";
    const fontSlug = siteData?.font || "outfit";

    if (!siteData || siteData.error) {
        return notFound();
    }

    // Get the selected font configuration
    const selectedFont = getFont(fontSlug);
    const allFontVariables = getAllFontVariables();

    // Build the list of theme class names for next-themes
    // const allThemeSlugs = getColorThemeMetadata().map((t) => t.slug);

    // Resolve the template's layout wrapper
    const template = getTemplate(templateSlug);
    const TemplateLayout = template.layout;

    return (
        <html lang="en" className={`${allFontVariables} ${colorThemeSlug}`}>
            <body
                className={`antialiased font-${fontSlug}`}
                style={{
                    fontFamily: `var(${selectedFont.variable})`,
                }}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme={colorThemeSlug}
                    enableSystem={false}
                    disableTransitionOnChange
                    // themes={allThemeSlugs}
                >
                    <TemplateLayout data={siteData}>{children}</TemplateLayout>
                </ThemeProvider>
            </body>
        </html>
    );
}
