import getSite from "@/lib/api";
import { notFound } from "next/navigation";
import { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { getFont, getAllFontVariables } from "@/lib/fonts";
import { readFile } from "fs/promises";
import path from "path";
import { DynamicLayout } from "@/components/dynamic-layout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

/**
 * Reads a single theme CSS file from disk and returns its contents.
 * Falls back to an empty string if the file can't be found.
 *
 * This runs server-side only, so the CSS for unused themes is never
 * shipped to the browser — each visitor receives only their site's theme.
 */
async function loadThemeCSS(slug: string): Promise<string> {
    // The slug may correspond to a base theme file (e.g. "amethyst-haze-dark"
    // lives inside "amethyst-haze.css"). Strip the "-dark" suffix to find
    // the right file, which contains both variants.
    const baseSlug = slug.endsWith("-dark") ? slug.slice(0, -5) : slug;

    // Resolve against the themes directory at src/themes/<base>.css.
    // __dirname is not available in ESM / Next.js app-dir, so we use
    // process.cwd() + the known relative path.
    const cssPath = path.join(
        process.cwd(),
        "src",
        "themes",
        `${baseSlug}.css`,
    );

    try {
        return await readFile(cssPath, "utf-8");
    } catch {
        console.warn(`Theme CSS file not found: ${cssPath}`);
        // Fallback to default if the requested file is missing
        if (baseSlug !== "default") {
            const fallbackPath = path.join(
                process.cwd(),
                "src",
                "themes",
                "default.css",
            );
            try {
                return await readFile(fallbackPath, "utf-8");
            } catch {
                return "";
            }
        }
        return "";
    }
}

export default async function DomainLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ domain: string }>;
}>) {
    const { domain } = await params;
    const siteData = await getSite(domain);

    // Get configuration from site data or use defaults
    const colorThemeSlug = siteData?.theme || "default";
    const templateSlug = siteData?.template || "default";
    const fontSlug = siteData?.font || "outfit";

    if (!siteData || siteData.error) {
        return notFound();
    }

    // Get the selected font configuration
    const selectedFont = getFont(fontSlug);
    const allFontVariables = getAllFontVariables();

    // Load only this site's theme CSS — runs on the server, zero bundle cost
    const themeCSS = await loadThemeCSS(colorThemeSlug);

    // Resolve the template's layout wrapper
    // The wrapper is dynamic for the preview functionality
    // const template = getTemplate(templateSlug);
    // const TemplateLayout = template.layout;

    return (
        <html lang="en" className={`${allFontVariables} ${colorThemeSlug}`}>
            <head>
                {/* Inject only the active theme's CSS — ~4KB vs ~150KB for all themes */}
                <style
                    dangerouslySetInnerHTML={{ __html: themeCSS }}
                    data-theme={colorThemeSlug}
                />
            </head>
            <body
                className={`antialiased font-${fontSlug}`}
                style={{
                    fontFamily: `var(${selectedFont.variable})`,
                }}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme={colorThemeSlug}
                    enableSystem={false}
                    disableTransitionOnChange
                >
                    <DynamicLayout data={siteData} domain={domain}>
                        {children}
                    </DynamicLayout>
                </ThemeProvider>
            </body>
        </html>
    );
}
