import getSite from "@/lib/api";
import { notFound } from "next/navigation";
import { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { themes } from "@/lib/themes";
import { TemplateProvider } from "@/contexts/template-context";
import { getFont, getAllFontVariables } from "@/lib/fonts";
import {
    getColorTheme,
    themeVariablesToCSSProperties,
} from "@/lib/color-themes";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function DomainLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ domain: string }>;
}>) {
    const { domain } = await params;
    const siteData = await getSite(domain);
    console.log("Site data:", siteData);

    // Get configuration from API or use defaults
    const colorThemeSlug = siteData?.theme || "default";
    const template = siteData?.template || "minimal";
    const fontSlug = siteData?.font || "outfit";

    console.log("Using color theme:", colorThemeSlug);
    console.log("Using template:", template);
    console.log("Using font:", fontSlug);

    if (!siteData || siteData.error) {
        return notFound();
    }

    // Get the selected font configuration
    const selectedFont = getFont(fontSlug);
    const allFontVariables = getAllFontVariables();

    // Get the selected color theme and convert to CSS properties
    const colorTheme = getColorTheme(colorThemeSlug);
    const themeStyles = themeVariablesToCSSProperties(colorTheme.variables);

    return (
        <html
            lang="en"
            className={allFontVariables}
            style={themeStyles as React.CSSProperties}
        >
            <body
                className={`antialiased font-${fontSlug}`}
                style={{
                    fontFamily: `var(${selectedFont.variable})`,
                }}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme={colorThemeSlug}
                    enableSystem
                    disableTransitionOnChange
                    themes={themes?.map((theme) => theme.value)}
                >
                    <TemplateProvider theme={template}>
                        {children}
                    </TemplateProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
